[package]
name = "danser-thing-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = { version = "0.10", default-features = true, features = ["framework", "standard_framework", "rustls_backend"]}
tokio = { version = "1.0",default-features = true, features = ["macros", "rt-multi-thread", "process"] }
dotenv = "0.15"
osu-db = { version = "*", default-features = false }
rosu-v2 = "0.3.0"
reqwest = { version = "0.11", default-features = false, features = ["json", "multipart", "rustls-tls"]}
mime_guess = { version = "2.0", default-features = false }
bytes = "1.0"
serde = { version = "1.0", features = ["derive"] }
zip = { version = "0.5" }
rosu-pp = "0.4.0"
serde_json = "1.0.48"